### ISSUE TITLE
Wrong prefix in prod infra json?

### ISSUE THREAD

**Issue by wischi-chr** [jochenvw/core-apps-demo#7]
Hi,

I just read through one of your [medium articles](https://medium.com/@jochenvanwylick/being-productive-working-with-arm-azure-resource-manager-templates-597bb1ba0b7f) _(great read btw.)_ and it referenced this repo.

I think there might be a bug (copy-paste error) in the prod infra json, because the prefix is the same as in the test group.

**Comment by jochenvw** [comment]
Hey @wischi-chr  - thanks for the feedback. I'll fix ASAP
